site_name: Groovin' Mod Framework Documentation
nav:
    - Home: index.md
    - Authors: authors.md
    - Da Basics: 
      - Environment Setup: tutorials/environment_setup.md
      - Framework Structure: tutorials/framework_structure.md
      - Asset Structure: tutorials/asset_structure.md
      - Creating a Mod: tutorials/creating_a_mod.md
    - Other Tutorials: 
      - How to Make an Actually Decent Modchart: tutorials/modcharting_guide.md
theme: readthedocs