site_name: Groovin' Mod Framework Documentation
nav:
    - Home: welcome.md
    - Authors: authors.md
    - Da Basics: 
      - Environment Setup: tutorials/environment_setup.md
      - Framework Structure: tutorials/framework_structure.md
      - Asset Structure: tutorials/asset_structure.md
      - Creating a Mod: tutorials/creating_a_mod.md
theme: readthedocs